services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000" 
    container_name: webapp-frontend
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306" 
    container_name: webapp-backend 
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: pizza_shop
      MYSQL_ROOT_PASSWORD: nazim
