services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80" 
    container_name: webapp-frontend 

  db:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3306:3306" 
    container_name: webapp-backend 
    environment:
      MYSQL_ROOT_PASSWORD: example
