services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80" 
    container_name: webapp-frontend 

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
